### ISSUE TITLE
Discovery script dont work

### ISSUE THREAD

**Issue by pavkamlc** [kerryland/zabbix-urbackup#1]
I tried monitor urbackup by your scripts, and it seems dont work. 
When I test discovery script manualy I get error. 
When I test url with suffix /x server return HTTP 404.
Depend your script on any version of the urbackup?

[root@backup3 zabbix-urbackup]# rpm -qa | grep urbackup
urbackup-server-2.5.33.0-1.1.x86_64
[root@backup3 zabbix-urbackup]# cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.10 (Ootpa)
[root@backup3 zabbix-urbackup]# python3 urbackup-discovery.py "http://backup.pavkamlc.cz:55414/x" "zabbix" "xxx"
Error during login. Password wrong?
[Traceback (most recent call last):
  File "/opt/zabbix-urbackup/urbackup-discovery.py", line 17, in <module>
    for client in server.get_status():
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

**Comment by kerryland** [comment]
I'm not using urbackup anymore. That code is actually from https://github.com/uroni/urbackup-server-python-web-api-wrapper so that's the best place to ask.

I assume zabbix and xxx are the correct user and password for urbackup?

Perhaps you need a newer version of python?

Sorry I don't have any better ideas

**Comment by pavkamlc** [comment]
I've tested this wrapper and it works. Problem was in selinux rules. With disabled selinux it works. Will be fine to write selinux rules for your template.

**Comment by kerryland** [comment]
I'm glad you found the problem. Thank you for taking the time to share the solution.
